// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fivwwotswaaypzlfdcol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdnd3b3Rzd2FheXB6bGZkY29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDEzMTYsImV4cCI6MjA2OTUxNzMxNn0.DxYYWN82Qaoxx6hXCRwLxdqP6mjSzTM3t_R9NjJOJLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});